app:
  name: ui
  image:
    repository: 'onecx/onecx-theme-ui'
  routing:
    enabled: true
  operator:
    apm:
      enabled: false
    keycloak:
      enabled: true
      client: |-
        { 
          "clientId": "theme-mgmt-ui",
          "enabled": true,
          "description": "Keycloak client for theme-mgmt-ui",
          "redirectUris": ["*"],
          "webOrigins": ["*"],
          "publicClient": true,
          "protocol": "openid-connect"
        }
      roles: |-
        [
           {
             "name": "onecx-theme-admin",
             "description": "OneCX Theme admin"
           },
           {
             "name": "onecx-theme-user",
             "description": "OneCX Theme user"
           }
         ]

# PIPE Config
